### ISSUE TITLE
Issue: couple of typos and import errors in scripts

### ISSUE THREAD

**Issue by ebonnassieux** [lmorabit/long_baseline_pipeline#96] opened 2023-06-08 10:06 UTC
Heya, just opening the issue because they're trivial fixes but recur whenever sourcing the code again:

on line 38 of bin/run_selfcal.py, "destifle" should be "destfile"
find_lotss_sources.py is missing "from time import sleep" leading to an uninformative bug when it crashes after a timeout

Otherwise things more or less run out of the box reliably which is fantastic!

**Comment by lmorabit** [comment] 2023-06-09 12:28
Thanks!

I've fixed run_selfcal.py, but I don't see where sleep is used in find_lotss_sources.py .  I am willing to believe the fix is needed, but can you please provide a bit more information as to why?

**Comment by lmorabit** [comment] 2023-08-07 07:47
@ebonnassieux waiting for further information to resolve or close this issue.

**Comment by jdswinbank** [comment] 2023-11-30 05:46
I'm guessing the problem is actually [here](https://github.com/lmorabit/lofar-vlbi/blob/a0dd0a7bf7cea5815b7611e030809d4ff94a5f54/plugins/PipelineStep_DownloadCats.py#L204)

**Closed as completed** 2023-11-30 07:44 UTC

**Comment by mhardcastle** [comment] 2023-11-30 07:46
Since this looks like it might have been my code once upon a time, I've pushed a fix to what @jdswinbank pointed out... @ebonnassieux please reopen if this is not the issue.
